#!/bin/bash

set -e

BUILD_DIR=build_cudaoptix
PYTHON=python3
COMMAND=$1

#rm -rf $BUILD_DIR

if [ -z "$COMMAND" ]
then
  COMMAND=Release
fi

#$PYTHON src/cmake/make_update.py

cmake -B $BUILD_DIR \
-DWITH_CYCLES_ALEMBIC=OFF \
-DWITH_CYCLES_EMBREE=OFF \
-DWITH_CYCLES_OPENCOLORIO=OFF \
-DWITH_CYCLES_OPENIMAGEDENOISE=OFF \
-DWITH_CYCLES_OPENSUBDIV=OFF \
-DWITH_CYCLES_OPENVDB=OFF \
-DWITH_CYCLES_NANOVDB=OFF \
-DWITH_CYCLES_OSL=OFF \
-DWITH_CYCLES_USD=OFF \
-DWITH_CYCLES_HYDRA_RENDER_DELEGATE=OFF \
-DWITH_CUDA_DYNLOAD=ON \
-DWITH_CYCLES_DEVICE_HIP=OFF \
-DWITH_CYCLES_HIP_BINARIES=OFF \
-DWITH_CYCLES_DEVICE_OPTIX=ON \
-DWITH_CYCLES_DEVICE_CUDA=ON \
-DWITH_CYCLES_CUDA_BINARIES=ON \
-DCYCLES_CUDA_BINARIES_ARCH="sm_37;sm_50;sm_52;sm_60;sm_61;sm_70;sm_75;sm_86;sm_89;compute_75" \
-DOPTIX_ROOT_DIR=/opt/optix76 \
-DCUDAToolkit_ROOT=/usr/local/cuda \
-DCUDA_PATH=/usr/local/cuda \
&& cd $BUILD_DIR && cmake --build . -j 8 --target install --config $COMMAND

#-DCYCLES_CUDA_BINARIES_ARCH="sm_89;compute_75" \

