#!/bin/bash

set -e

BUILD_DIR=build_oneapi
PYTHON=python3
COMMAND=$1

if [ -z "$COMMAND" ]
then
  COMMAND=Release
fi

$PYTHON src/cmake/make_update.py

cmake -B $BUILD_DIR \
-DWITH_CYCLES_ALEMBIC=OFF \
-DWITH_CYCLES_EMBREE=OFF \
-DWITH_CYCLES_OPENCOLORIO=OFF \
-DWITH_CYCLES_OPENIMAGEDENOISE=OFF \
-DWITH_CYCLES_OPENSUBDIV=OFF \
-DWITH_CYCLES_OPENVDB=OFF \
-DWITH_CYCLES_NANOVDB=OFF \
-DWITH_CYCLES_OSL=OFF \
-DWITH_CYCLES_USD=OFF \
-DWITH_CYCLES_HYDRA_RENDER_DELEGATE=OFF \
-DWITH_CYCLES_CUDA_BINARIES=OFF \
-DWITH_CYCLES_DEVICE_OPTIX=OFF \
-DWITH_CUDA_DYNLOAD=OFF \
-DWITH_CYCLES_DEVICE_ONEAPI=ON \
-DWITH_CYCLES_ONEAPI_BINARIES=ON \
&& cd $BUILD_DIR && cmake --build . --target install --config $COMMAND
