/**
Copyright 2014-2025 Robert McNeel and Associates
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----------------------------------------------------------------------
NOTE: Do NOT modify this file directly, it is automatically generated.
Code generated at: 2025-11-25 13:56:53 UTC
----------------------------------------------------------------------
**/
namespace ccl
{
    public enum ShaderNodeType : uint
    {
        NODE_END = 0,
        NODE_SHADER_JUMP = 1,
        NODE_CLOSURE_BSDF = 2,
        NODE_CLOSURE_EMISSION = 3,
        NODE_CLOSURE_BACKGROUND = 4,
        NODE_CLOSURE_SET_WEIGHT = 5,
        NODE_CLOSURE_WEIGHT = 6,
        NODE_EMISSION_WEIGHT = 7,
        NODE_MIX_CLOSURE = 8,
        NODE_JUMP_IF_ZERO = 9,
        NODE_JUMP_IF_ONE = 10,
        NODE_GEOMETRY = 11,
        NODE_CONVERT = 12,
        NODE_TEX_COORD = 13,
        NODE_VALUE_F = 14,
        NODE_VALUE_V = 15,
        NODE_ATTR = 16,
        NODE_VERTEX_COLOR = 17,
        NODE_GEOMETRY_BUMP_DX = 18,
        NODE_GEOMETRY_BUMP_DY = 19,
        NODE_SET_DISPLACEMENT = 20,
        NODE_DISPLACEMENT = 21,
        NODE_VECTOR_DISPLACEMENT = 22,
        NODE_TEX_IMAGE = 23,
        NODE_TEX_IMAGE_BOX = 24,
        NODE_TEX_NOISE = 25,
        NODE_SET_BUMP = 26,
        NODE_ATTR_BUMP_DX = 27,
        NODE_ATTR_BUMP_DY = 28,
        NODE_VERTEX_COLOR_BUMP_DX = 29,
        NODE_VERTEX_COLOR_BUMP_DY = 30,
        NODE_TEX_COORD_BUMP_DX = 31,
        NODE_TEX_COORD_BUMP_DY = 32,
        NODE_CLOSURE_SET_NORMAL = 33,
        NODE_ENTER_BUMP_EVAL = 34,
        NODE_LEAVE_BUMP_EVAL = 35,
        NODE_HSV = 36,
        NODE_CLOSURE_HOLDOUT = 37,
        NODE_FRESNEL = 38,
        NODE_LAYER_WEIGHT = 39,
        NODE_CLOSURE_VOLUME = 40,
        NODE_PRINCIPLED_VOLUME = 41,
        NODE_MATH = 42,
        NODE_VECTOR_MATH = 43,
        NODE_RGB_RAMP = 44,
        NODE_GAMMA = 45,
        NODE_BRIGHTCONTRAST = 46,
        NODE_LIGHT_PATH = 47,
        NODE_OBJECT_INFO = 48,
        NODE_PARTICLE_INFO = 49,
        NODE_HAIR_INFO = 50,
        NODE_POINT_INFO = 51,
        NODE_TEXTURE_MAPPING = 52,
        NODE_MAPPING = 53,
        NODE_MIN_MAX = 54,
        NODE_CAMERA = 55,
        NODE_TEX_ENVIRONMENT = 56,
        NODE_TEX_SKY = 57,
        NODE_TEX_GRADIENT = 58,
        NODE_TEX_VORONOI = 59,
        NODE_TEX_GABOR = 60,
        NODE_TEX_WAVE = 61,
        NODE_TEX_MAGIC = 62,
        NODE_TEX_CHECKER = 63,
        NODE_TEX_BRICK = 64,
        NODE_TEX_WHITE_NOISE = 65,
        NODE_NORMAL = 66,
        NODE_LIGHT_FALLOFF = 67,
        NODE_IES = 68,
        NODE_CURVES = 69,
        NODE_TANGENT = 70,
        NODE_NORMAL_MAP = 71,
        NODE_INVERT = 72,
        NODE_MIX = 73,
        NODE_SEPARATE_COLOR = 74,
        NODE_COMBINE_COLOR = 75,
        NODE_SEPARATE_VECTOR = 76,
        NODE_COMBINE_VECTOR = 77,
        NODE_SEPARATE_HSV = 78,
        NODE_COMBINE_HSV = 79,
        NODE_VECTOR_ROTATE = 80,
        NODE_VECTOR_TRANSFORM = 81,
        NODE_WIREFRAME = 82,
        NODE_WAVELENGTH = 83,
        NODE_BLACKBODY = 84,
        NODE_MAP_RANGE = 85,
        NODE_VECTOR_MAP_RANGE = 86,
        NODE_CLAMP = 87,
        NODE_BEVEL = 88,
        NODE_AMBIENT_OCCLUSION = 89,
        NODE_TEX_VOXEL = 90,
        NODE_AOV_START = 91,
        NODE_AOV_COLOR = 92,
        NODE_AOV_VALUE = 93,
        NODE_FLOAT_CURVE = 94,
        NODE_MIX_COLOR = 95,
        NODE_MIX_FLOAT = 96,
        NODE_MIX_VECTOR = 97,
        NODE_MIX_VECTOR_NON_UNIFORM = 98,
        RHINO_NODE_TEX_COORD = 99,
        RHINO_NODE_MATRIX_MATH = 100,
        RHINO_NODE_AZIMUTH_ALTITUDE_TRANSFORM = 101,
        RHINO_NODE_CHECKER_TEXTURE = 102,
        RHINO_NODE_NOISE_TEXTURE = 103,
        RHINO_NODE_WAVES_TEXTURE = 104,
        RHINO_NODE_WAVES_WIDTH_TEXTURE = 105,
        RHINO_NODE_PERTURBING_PART1_TEXTURE = 106,
        RHINO_NODE_PERTURBING_PART2_TEXTURE = 107,
        RHINO_NODE_GRADIENT_TEXTURE = 108,
        RHINO_NODE_BLEND_TEXTURE = 109,
        RHINO_NODE_EXPOSURE_TEXTURE = 110,
        RHINO_NODE_FBM_TEXTURE = 111,
        RHINO_NODE_GRID_TEXTURE = 112,
        RHINO_NODE_PROJECTION_CHANGER_TEXTURE = 113,
        RHINO_NODE_MASK_TEXTURE = 114,
        RHINO_NODE_PERLIN_MARBLE_TEXTURE = 115,
        RHINO_NODE_PHYSICAL_SKY_TEXTURE = 116,
        RHINO_NODE_TEXTURE_ADJUSTMENT_TEXTURE = 117,
        RHINO_NODE_TILE_TEXTURE = 118,
        RHINO_NODE_DOTS_TEXTURE = 119,
        RHINO_NODE_NORMAL_PART1_TEXTURE = 120,
        RHINO_NODE_NORMAL_PART2_TEXTURE = 121,
        NODE_PAD1 = 122,
        NODE_PAD2 = 123,
        NODE_NUM = 124,
    }
}
